# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pages.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cx_Oracle
import mydb.db
import sys
import os
from prettytable import PrettyTable 
from PyQt5 import QtCore, QtGui, QtWidgets

SPECIALIZARI_HEADER =['ID','Specializare','Facultate','Locuri disponibile']
STUDENTI_HEADER = ["id", "nume","prenume","Specializare","Faculate", "Data_Nasterii", "adresa", "telefon", "email"]
class Ui_MainWindow(object):
            
    def exit_funct(self):
        sys.exit(1)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 608)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.HeaderFrame = QtWidgets.QFrame(self.centralwidget)
        self.HeaderFrame.setGeometry(QtCore.QRect(0, -10, 931, 71))
        self.HeaderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HeaderFrame.setObjectName("HeaderFrame")
        self.me_name = QtWidgets.QLabel(self.HeaderFrame)
        self.me_name.setGeometry(QtCore.QRect(30, 20, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.me_name.setFont(font)
        self.me_name.setObjectName("me_name")
        self.label_2 = QtWidgets.QLabel(self.HeaderFrame)
        self.label_2.setGeometry(QtCore.QRect(680, 20, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 50, 931, 501))
        self.stackedWidget.setObjectName("stackedWidget")
        self.starting_page = QtWidgets.QWidget()
        self.starting_page.setObjectName("starting_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.starting_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.exit_btn1 = QtWidgets.QPushButton(self.starting_page)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.exit_btn1.setFont(font)
        self.exit_btn1.setAutoRepeatInterval(98)
        self.exit_btn1.setObjectName("exit_btn1")
        self.verticalLayout.addWidget(self.exit_btn1)
        self.pushButton_2 = QtWidgets.QPushButton(self.starting_page)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.stackedWidget.addWidget(self.starting_page)
        self.content_page = QtWidgets.QWidget()
        self.content_page.setObjectName("content_page")
        self.studenti_btn = QtWidgets.QPushButton(self.content_page)
        self.studenti_btn.setGeometry(QtCore.QRect(10, 20, 201, 51))
        self.studenti_btn.setObjectName("studenti_btn")
        self.facultati_btn = QtWidgets.QPushButton(self.content_page)
        self.facultati_btn.setGeometry(QtCore.QRect(10, 80, 201, 51))
        self.facultati_btn.setObjectName("facultati_btn")
        self.specializar_btn = QtWidgets.QPushButton(self.content_page)
        self.specializar_btn.setGeometry(QtCore.QRect(10, 140, 201, 51))
        self.specializar_btn.setObjectName("specializar_btn")
        self.content_widget = QtWidgets.QStackedWidget(self.content_page)
        self.content_widget.setGeometry(QtCore.QRect(220, 10, 721, 501))
        self.content_widget.setObjectName("content_widget")
        self.facultati_sp_widget = QtWidgets.QWidget()
        self.facultati_sp_widget.setObjectName("facultati_sp_widget")
        self.name_insert_2 = QtWidgets.QLineEdit(self.facultati_sp_widget)
        self.name_insert_2.setGeometry(QtCore.QRect(150, 390, 61, 20))
        self.name_insert_2.setObjectName("name_insert_2")
        self.prenume_insert_2 = QtWidgets.QLineEdit(self.facultati_sp_widget)
        self.prenume_insert_2.setGeometry(QtCore.QRect(290, 390, 151, 20))
        self.prenume_insert_2.setObjectName("prenume_insert_2")
        self.sort_age_ckbox_2 = QtWidgets.QCheckBox(self.facultati_sp_widget)
        self.sort_age_ckbox_2.setGeometry(QtCore.QRect(520, 90, 70, 17))
        self.sort_age_ckbox_2.setObjectName("sort_age_ckbox_2")
        self.email_insert_2 = QtWidgets.QLineEdit(self.facultati_sp_widget)
        self.email_insert_2.setGeometry(QtCore.QRect(150, 420, 61, 20))
        self.email_insert_2.setText("")
        self.email_insert_2.setObjectName("email_insert_2")
        self.name_delete_2 = QtWidgets.QLineEdit(self.facultati_sp_widget)
        self.name_delete_2.setGeometry(QtCore.QRect(290, 450, 81, 20))
        self.name_delete_2.setObjectName("name_delete_2")
        self.sort_desc_ckbox_2 = QtWidgets.QCheckBox(self.facultati_sp_widget)
        self.sort_desc_ckbox_2.setGeometry(QtCore.QRect(590, 80, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sort_desc_ckbox_2.setFont(font)
        self.sort_desc_ckbox_2.setObjectName("sort_desc_ckbox_2")
        self.listView_filter_2 = QtWidgets.QListView(self.facultati_sp_widget)
        self.listView_filter_2.setGeometry(QtCore.QRect(0, 150, 711, 221))
        self.listView_filter_2.setObjectName("listView_filter_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.facultati_sp_widget)
        self.pushButton_6.setGeometry(QtCore.QRect(570, 420, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.facultati_sp_widget)
        self.pushButton_8.setGeometry(QtCore.QRect(390, 110, 311, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_52 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.label_52.setGeometry(QtCore.QRect(0, 390, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.sort_name_chckbox_2 = QtWidgets.QCheckBox(self.facultati_sp_widget)
        self.sort_name_chckbox_2.setGeometry(QtCore.QRect(390, 90, 70, 17))
        self.sort_name_chckbox_2.setObjectName("sort_name_chckbox_2")
        self.label_51 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.label_51.setGeometry(QtCore.QRect(100, 450, 47, 13))
        self.label_51.setObjectName("label_51")
        self.pushButton_7 = QtWidgets.QPushButton(self.facultati_sp_widget)
        self.pushButton_7.setGeometry(QtCore.QRect(390, 450, 111, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_50 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.label_50.setGeometry(QtCore.QRect(110, 420, 47, 13))
        self.label_50.setObjectName("label_50")
        self.name_filter_2 = QtWidgets.QLineEdit(self.facultati_sp_widget)
        self.name_filter_2.setGeometry(QtCore.QRect(80, 120, 91, 20))
        self.name_filter_2.setObjectName("name_filter_2")
        self.label_46 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.label_46.setGeometry(QtCore.QRect(390, 60, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.filter_name_2 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.filter_name_2.setGeometry(QtCore.QRect(20, 60, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.filter_name_2.setFont(font)
        self.filter_name_2.setObjectName("filter_name_2")
        self.lbl_name_studenti_sp_4 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.lbl_name_studenti_sp_4.setGeometry(QtCore.QRect(10, 0, 681, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lbl_name_studenti_sp_4.setFont(font)
        self.lbl_name_studenti_sp_4.setObjectName("lbl_name_studenti_sp_4")
        self.label_44 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.label_44.setGeometry(QtCore.QRect(80, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.address_insert_2 = QtWidgets.QLineEdit(self.facultati_sp_widget)
        self.address_insert_2.setGeometry(QtCore.QRect(270, 420, 291, 20))
        self.address_insert_2.setText("")
        self.address_insert_2.setObjectName("address_insert_2")
        self.id_filter_2 = QtWidgets.QLineEdit(self.facultati_sp_widget)
        self.id_filter_2.setGeometry(QtCore.QRect(0, 120, 61, 20))
        self.id_filter_2.setObjectName("id_filter_2")
        self.label_49 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.label_49.setGeometry(QtCore.QRect(230, 420, 47, 13))
        self.label_49.setObjectName("label_49")
        self.label_53 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.label_53.setGeometry(QtCore.QRect(0, 440, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_48 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.label_48.setGeometry(QtCore.QRect(110, 390, 47, 13))
        self.label_48.setObjectName("label_48")
        self.label_42 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.label_42.setGeometry(QtCore.QRect(20, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.sort_prenume_ckbox_2 = QtWidgets.QCheckBox(self.facultati_sp_widget)
        self.sort_prenume_ckbox_2.setGeometry(QtCore.QRect(450, 90, 70, 17))
        self.sort_prenume_ckbox_2.setObjectName("sort_prenume_ckbox_2")
        self.label_39 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.label_39.setGeometry(QtCore.QRect(230, 450, 47, 13))
        self.label_39.setObjectName("label_39")
        self.id_delete_2 = QtWidgets.QLineEdit(self.facultati_sp_widget)
        self.id_delete_2.setGeometry(QtCore.QRect(160, 450, 41, 20))
        self.id_delete_2.setObjectName("id_delete_2")
        self.label_47 = QtWidgets.QLabel(self.facultati_sp_widget)
        self.label_47.setGeometry(QtCore.QRect(230, 390, 47, 13))
        self.label_47.setObjectName("label_47")
        self.content_widget.addWidget(self.facultati_sp_widget)
        self.studenti_sp_widget = QtWidgets.QWidget()
        self.studenti_sp_widget.setObjectName("studenti_sp_widget")
        self.lbl_name_studenti_sp = QtWidgets.QLabel(self.studenti_sp_widget)
        self.lbl_name_studenti_sp.setGeometry(QtCore.QRect(10, 10, 681, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lbl_name_studenti_sp.setFont(font)
        self.lbl_name_studenti_sp.setObjectName("lbl_name_studenti_sp")
        self.filter_name = QtWidgets.QLabel(self.studenti_sp_widget)
        self.filter_name.setGeometry(QtCore.QRect(20, 70, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.filter_name.setFont(font)
        self.filter_name.setObjectName("filter_name")
        self.label_3 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_4.setGeometry(QtCore.QRect(80, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_5.setGeometry(QtCore.QRect(190, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_6.setGeometry(QtCore.QRect(300, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_8.setGeometry(QtCore.QRect(390, 70, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.id_filter = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.id_filter.setGeometry(QtCore.QRect(0, 130, 61, 20))
        self.id_filter.setObjectName("id_filter")
        self.name_filter = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.name_filter.setGeometry(QtCore.QRect(80, 130, 91, 20))
        self.name_filter.setObjectName("name_filter")
        self.prenume_filter = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.prenume_filter.setGeometry(QtCore.QRect(190, 130, 91, 20))
        self.prenume_filter.setObjectName("prenume_filter")
        self.phone_filter = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.phone_filter.setGeometry(QtCore.QRect(300, 130, 71, 20))
        self.phone_filter.setObjectName("phone_filter")
        self.sort_name_chckbox = QtWidgets.QCheckBox(self.studenti_sp_widget)
        self.sort_name_chckbox.setGeometry(QtCore.QRect(390, 100, 70, 17))
        self.sort_name_chckbox.setObjectName("sort_name_chckbox")
        self.sort_prenume_ckbox = QtWidgets.QCheckBox(self.studenti_sp_widget)
        self.sort_prenume_ckbox.setGeometry(QtCore.QRect(450, 100, 70, 17))
        self.sort_prenume_ckbox.setObjectName("sort_prenume_ckbox")
        self.sort_age_ckbox = QtWidgets.QCheckBox(self.studenti_sp_widget)
        self.sort_age_ckbox.setGeometry(QtCore.QRect(520, 100, 70, 17))
        self.sort_age_ckbox.setObjectName("sort_age_ckbox")
        self.sort_desc_ckbox = QtWidgets.QCheckBox(self.studenti_sp_widget)
        self.sort_desc_ckbox.setGeometry(QtCore.QRect(590, 90, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sort_desc_ckbox.setFont(font)
        self.sort_desc_ckbox.setObjectName("sort_desc_ckbox")
        self.listView_filter = QtWidgets.QListView(self.studenti_sp_widget)
        self.listView_filter.setGeometry(QtCore.QRect(0, 160, 711, 221))
        self.listView_filter.setObjectName("listView_filter")
        self.pushButton = QtWidgets.QPushButton(self.studenti_sp_widget)
        self.pushButton.setGeometry(QtCore.QRect(390, 120, 311, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_7.setGeometry(QtCore.QRect(0, 400, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_17 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_17.setGeometry(QtCore.QRect(110, 400, 47, 13))
        self.label_17.setObjectName("label_17")
        self.name_insert = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.name_insert.setGeometry(QtCore.QRect(150, 400, 61, 20))
        self.name_insert.setObjectName("name_insert")
        self.prenume_insert = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.prenume_insert.setGeometry(QtCore.QRect(290, 400, 61, 20))
        self.prenume_insert.setObjectName("prenume_insert")
        self.label_18 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_18.setGeometry(QtCore.QRect(230, 400, 47, 13))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_19.setGeometry(QtCore.QRect(370, 400, 111, 16))
        self.label_19.setObjectName("label_19")
        self.date_insert = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.date_insert.setGeometry(QtCore.QRect(450, 400, 61, 20))
        self.date_insert.setObjectName("date_insert")
        self.label_20 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_20.setGeometry(QtCore.QRect(520, 400, 47, 13))
        self.label_20.setObjectName("label_20")
        self.phone_insert = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.phone_insert.setGeometry(QtCore.QRect(570, 400, 71, 20))
        self.phone_insert.setText("")
        self.phone_insert.setObjectName("phone_insert")
        self.email_insert = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.email_insert.setGeometry(QtCore.QRect(150, 430, 61, 20))
        self.email_insert.setText("")
        self.email_insert.setObjectName("email_insert")
        self.label_33 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_33.setGeometry(QtCore.QRect(110, 430, 47, 13))
        self.label_33.setObjectName("label_33")
        self.address_insert = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.address_insert.setGeometry(QtCore.QRect(270, 430, 141, 20))
        self.address_insert.setText("")
        self.address_insert.setObjectName("address_insert")
        self.label_34 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_34.setGeometry(QtCore.QRect(230, 430, 47, 13))
        self.label_34.setObjectName("label_34")
        self.pushButton_4 = QtWidgets.QPushButton(self.studenti_sp_widget)
        self.pushButton_4.setGeometry(QtCore.QRect(630, 430, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_35 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_35.setGeometry(QtCore.QRect(0, 450, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_36.setGeometry(QtCore.QRect(100, 460, 47, 13))
        self.label_36.setObjectName("label_36")
        self.id_delete = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.id_delete.setGeometry(QtCore.QRect(160, 460, 41, 20))
        self.id_delete.setObjectName("id_delete")
        self.label_37 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_37.setGeometry(QtCore.QRect(230, 460, 47, 13))
        self.label_37.setObjectName("label_37")
        self.name_delete = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.name_delete.setGeometry(QtCore.QRect(290, 460, 81, 20))
        self.name_delete.setObjectName("name_delete")
        self.label_38 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_38.setGeometry(QtCore.QRect(400, 460, 47, 13))
        self.label_38.setObjectName("label_38")
        self.prenume_delete = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.prenume_delete.setGeometry(QtCore.QRect(450, 460, 81, 20))
        self.prenume_delete.setObjectName("prenume_delete")
        self.pushButton_5 = QtWidgets.QPushButton(self.studenti_sp_widget)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 460, 111, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.address_insert_4 = QtWidgets.QLineEdit(self.studenti_sp_widget)
        self.address_insert_4.setGeometry(QtCore.QRect(490, 430, 141, 20))
        self.address_insert_4.setText("")
        self.address_insert_4.setObjectName("address_insert_4")
        self.label_41 = QtWidgets.QLabel(self.studenti_sp_widget)
        self.label_41.setGeometry(QtCore.QRect(416, 430, 61, 20))
        self.label_41.setObjectName("label_41")
        self.content_widget.addWidget(self.studenti_sp_widget)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_9 = QtWidgets.QPushButton(self.page)
        self.pushButton_9.setGeometry(QtCore.QRect(570, 430, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_54 = QtWidgets.QLabel(self.page)
        self.label_54.setGeometry(QtCore.QRect(110, 430, 101, 16))
        self.label_54.setObjectName("label_54")
        self.prenume_insert_3 = QtWidgets.QLineEdit(self.page)
        self.prenume_insert_3.setGeometry(QtCore.QRect(350, 400, 151, 20))
        self.prenume_insert_3.setObjectName("prenume_insert_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.page)
        self.pushButton_10.setGeometry(QtCore.QRect(390, 120, 311, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_55 = QtWidgets.QLabel(self.page)
        self.label_55.setGeometry(QtCore.QRect(390, 70, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.lbl_name_studenti_sp_5 = QtWidgets.QLabel(self.page)
        self.lbl_name_studenti_sp_5.setGeometry(QtCore.QRect(10, 10, 681, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lbl_name_studenti_sp_5.setFont(font)
        self.lbl_name_studenti_sp_5.setObjectName("lbl_name_studenti_sp_5")
        self.name_delete_3 = QtWidgets.QLineEdit(self.page)
        self.name_delete_3.setGeometry(QtCore.QRect(290, 460, 81, 20))
        self.name_delete_3.setObjectName("name_delete_3")
        self.name_insert_3 = QtWidgets.QLineEdit(self.page)
        self.name_insert_3.setGeometry(QtCore.QRect(150, 400, 61, 20))
        self.name_insert_3.setObjectName("name_insert_3")
        self.name_filter_3 = QtWidgets.QLineEdit(self.page)
        self.name_filter_3.setGeometry(QtCore.QRect(80, 130, 91, 20))
        self.name_filter_3.setObjectName("name_filter_3")
        self.label_56 = QtWidgets.QLabel(self.page)
        self.label_56.setGeometry(QtCore.QRect(0, 400, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.id_filter_3 = QtWidgets.QLineEdit(self.page)
        self.id_filter_3.setGeometry(QtCore.QRect(0, 130, 61, 20))
        self.id_filter_3.setObjectName("id_filter_3")
        self.label_45 = QtWidgets.QLabel(self.page)
        self.label_45.setGeometry(QtCore.QRect(80, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.sort_prenume_ckbox_3 = QtWidgets.QCheckBox(self.page)
        self.sort_prenume_ckbox_3.setGeometry(QtCore.QRect(410, 100, 111, 17))
        self.sort_prenume_ckbox_3.setObjectName("sort_prenume_ckbox_3")
        self.sort_desc_ckbox_3 = QtWidgets.QCheckBox(self.page)
        self.sort_desc_ckbox_3.setGeometry(QtCore.QRect(590, 90, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sort_desc_ckbox_3.setFont(font)
        self.sort_desc_ckbox_3.setObjectName("sort_desc_ckbox_3")
        self.label_40 = QtWidgets.QLabel(self.page)
        self.label_40.setGeometry(QtCore.QRect(230, 460, 47, 13))
        self.label_40.setObjectName("label_40")
        self.sort_name_chckbox_3 = QtWidgets.QCheckBox(self.page)
        self.sort_name_chckbox_3.setGeometry(QtCore.QRect(350, 100, 70, 17))
        self.sort_name_chckbox_3.setObjectName("sort_name_chckbox_3")
        self.email_insert_3 = QtWidgets.QLineEdit(self.page)
        self.email_insert_3.setGeometry(QtCore.QRect(180, 430, 321, 20))
        self.email_insert_3.setText("")
        self.email_insert_3.setObjectName("email_insert_3")
        self.sort_age_ckbox_3 = QtWidgets.QCheckBox(self.page)
        self.sort_age_ckbox_3.setGeometry(QtCore.QRect(520, 100, 70, 17))
        self.sort_age_ckbox_3.setObjectName("sort_age_ckbox_3")
        self.label_58 = QtWidgets.QLabel(self.page)
        self.label_58.setGeometry(QtCore.QRect(0, 450, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.page)
        self.label_59.setGeometry(QtCore.QRect(230, 400, 101, 16))
        self.label_59.setObjectName("label_59")
        self.id_delete_3 = QtWidgets.QLineEdit(self.page)
        self.id_delete_3.setGeometry(QtCore.QRect(160, 460, 41, 20))
        self.id_delete_3.setObjectName("id_delete_3")
        self.label_60 = QtWidgets.QLabel(self.page)
        self.label_60.setGeometry(QtCore.QRect(110, 400, 47, 13))
        self.label_60.setObjectName("label_60")
        self.filter_name_3 = QtWidgets.QLabel(self.page)
        self.filter_name_3.setGeometry(QtCore.QRect(20, 70, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.filter_name_3.setFont(font)
        self.filter_name_3.setObjectName("filter_name_3")
        self.pushButton_11 = QtWidgets.QPushButton(self.page)
        self.pushButton_11.setGeometry(QtCore.QRect(390, 460, 111, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_43 = QtWidgets.QLabel(self.page)
        self.label_43.setGeometry(QtCore.QRect(20, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.listView_filter_3 = QtWidgets.QListView(self.page)
        self.listView_filter_3.setGeometry(QtCore.QRect(0, 160, 711, 221))
        self.listView_filter_3.setObjectName("listView_filter_3")
        self.label_61 = QtWidgets.QLabel(self.page)
        self.label_61.setGeometry(QtCore.QRect(100, 460, 47, 13))
        self.label_61.setObjectName("label_61")
        self.name_filter_4 = QtWidgets.QLineEdit(self.page)
        self.name_filter_4.setGeometry(QtCore.QRect(190, 130, 91, 20))
        self.name_filter_4.setText("")
        self.name_filter_4.setObjectName("name_filter_4")
        self.label_62 = QtWidgets.QLabel(self.page)
        self.label_62.setGeometry(QtCore.QRect(190, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.content_widget.addWidget(self.page)
        self.stackedWidget.addWidget(self.content_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.content_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.exit_btn1.clicked.connect(self.set_content_page)
        self.pushButton_2.clicked.connect(self.exit_btn)
        self.facultati_btn.clicked.connect(self.set_facultati_widget)
        self.specializar_btn.clicked.connect(self.set_specialziare_widget)
        self.studenti_btn.clicked.connect(self.set_studenti_widget)
        self.pushButton_8.clicked.connect(self.set_filter_btn)
        self.pushButton_6.clicked.connect(self.insert_facultate)
        self.pushButton_7.clicked.connect(self.delete_facultate)
        self.pushButton_10.clicked.connect(self.set_filter_btn_specializari)
        self.pushButton_9.clicked.connect(self.insert_specializare)
        self.pushButton_11.clicked.connect(self.delete_specializare)
        self.pushButton.clicked.connect(self.set_filter_btn_studenti)
        self.pushButton_4.clicked.connect(self.insert_student)
        self.pushButton_5.clicked.connect(self.delete_student)
        # self.specializar_btn.clicked.connect(self.)
        self.model = QtCore.QStringListModel()
        self.model_specializari  = QtCore.QStringListModel()
        self.model_studenti = QtCore.QStringListModel()
        self.listView_filter_2.setModel(self.model)
        self.listView_filter_3.setModel(self.model_specializari)
        self.listView_filter.setModel(self.model_studenti)
    def insert_student(self):
        querryString = ''
        querryString+=f"(ID, Nume, Prenume, ID_Specializare, Data_Nasterii, Adresa, Telefon, Email) VALUES ("
        try:
            querryString+= str(mydb.db.get_max_id('Studenti_SP')+1)
        except Exception as e:
            querryString+= '1'
        if self.name_insert.text()=='':
            raise Exception('Numele nu poate fi null')    
        
        if self.prenume_insert.text()=='':
            self.prenume_insert.setText('-')
        
        if self.date_insert.text()=='':
            self.date_insert.setText('2000-01-01')
        if self.address_insert.text()=='':
            self.date_insert.setText('-')
        if self.phone_insert.text()=='':
            self.phone_insert.setText('-')
        if self.email_insert.text()=='':
            self.email_insert.setText('-')
        if self.address_insert_4.text()=='':
            self.address_insert_4.setText('-')
        try:
            querryString+=f", '{self.name_insert.text()}', '{self.prenume_insert.text()}', {mydb.db.selectare_id_specializare(self.address_insert_4.text())}, to_date('{self.date_insert.text()}','YYYY-MM-DD'), '{self.address_insert.text()}', '{self.phone_insert.text()}', '{self.email_insert.text()}')"
            print(querryString)
        except:
            pass
        
        try:
            mydb.db.insert_into_table('studenti_sp',querryString)
        except Exception as e:
            print(e)
        
        self.set_filter_btn_studenti()
        
    def delete_student(self):
        if self.id_delete.text() !='':
            querryString = ' Where ID='+self.id_delete.text()
        else:
            if self.name_delete.text()  != '':
                querryString = f" Where Nume='{self.name_delete.text()}'"
                
        try:
            
            mydb.db.delete_where('Studenti_SP',querryString)
        except Exception:
            pass
        self.set_filter_btn_studenti()
    def set_filter_btn_studenti(self):
        querryString = "WHERE "
        first = False
        
        if (self.phone_filter.text()!=''):
            print(type(self.phone_filter.text()))
            check_int= False
            try:
                value = int(self.phone_filter.text())
                check_int = True
            except:
                check_int = False
            if check_int:
                if first == True:
                    querryString+=f"AND "   
                querryString+=f"f.id={self.phone_filter.text()} "
                first = True
            else:
                if first == True:
                    querryString+=f"AND "
                try:   
                    querryString+=f"f.id='{mydb.db.selectare_id_facultate(self.phone_filter.text())}' "
                except:
                    pass
            first = True 
        if (self.id_filter.text()!=''):

            querryString+=f"s.ID={self.id_filter.text()} "
            first = True
        if (self.name_filter.text()!=''):
            if first == True:
                querryString+=f"AND "   
            querryString+=f"s.Nume='{self.name_filter.text()}' "
            first = True
        if (self.prenume_filter.text()!=''):
            if first == True:
                querryString+=f"AND "   
            querryString+=f"s.prenume='{self.prenume_filter.text()}' "
            first = True    
        # if(self.phone_filter.text()!=''):
        #     if first == True:
        #         querryString+=f"AND "
        #     querryString+=f"f.nume='{self.phone_filter.text()}' "
        print('Final ', querryString)
        orderString = 'ORDER BY '
        first = False
        print(querryString)     
        if self.sort_name_chckbox.isChecked():
            if self.sort_desc_ckbox.isChecked():
                
                orderString+='s.nume DESC'
            else:
                orderString+='s.nume ASC'
            first = True
        if self.sort_prenume_ckbox.isChecked():
            if first:
                if self.sort_desc_ckbox.isChecked():
                    
                    orderString+=', s.prenume DESC'
                else:
                    orderString+=', s.prenume  ASC'
            else:
                if self.sort_desc_ckbox.isChecked():
                    
                    orderString+=' s.prenume DESC'
                else:
                    orderString+=' s.prenume ASC'
            first = True
        
        if self.sort_age_ckbox.isChecked():
            if first:
                if self.sort_desc_ckbox.isChecked():
                    
                    orderString+=', s.Data_Nasterii DESC'
                else:
                    orderString+=', s.Data_Nasterii ASC'
            else:
                if self.sort_desc_ckbox.isChecked():
                    
                    orderString+=' s.Data_Nasterii DESC'
                else:
                    orderString+=' s.Data_Nasterii ASC'
            first = True
        if self.sort_prenume_ckbox.isChecked():
            if first:
                if self.sort_desc_ckbox.isChecked():
                    
                    orderString+=', s.prenume DESC'
                else:
                    orderString+=', s.prenume ASC'
            else:
                if self.sort_desc_ckbox.isChecked():
                    
                    orderString+=' s.prenume DESC'
                else:
                    orderString+=' s.prenume ASC'
            first = True
        print('final order by ',orderString)
        if querryString!='WHERE ':
            if orderString!='ORDER BY ':
                querryString+=orderString
            output = mydb.db.select_studenti_specializari_where(querryString)
           
        else:
            if orderString!='ORDER BY ':
                # output = mydb.db.select_with_where(orderString,'Specializari_SP')
                output = mydb.db.select_studenti_specializari_where(querryString)
            else:
                output = mydb.db.select_Studenti_specializari()
        self.create_table_facultati(STUDENTI_HEADER,output,studenti=True)
                
        
        pass        
    def delete_specializare(self):
        if self.id_delete_3.text() !='':
            querryString = ' Where ID='+self.id_delete_3.text()
        else:
            if self.name_delete_3.text()  != '':
                querryString = f" Where Nume='{self.name_delete_3.text()}'"
                
        try:
            
            mydb.db.delete_where('Specializari_SP',querryString)
        except Exception:
            pass
        self.set_filter_btn_specializari()
    def insert_specializare(self):
        querryString = ''
            # INSERT INTO Facultati_SP (ID, Nume, Adresa, Telefon, Email)
# VALUES (4, 'Facultatea de Drept', 'Strada Dreptului, Suceava', '+40 230 111 222', 'info@facultatededrept.usv.ro');
        # 'ID','Specializare','Facultate','Locuri disponibile'
        # ID, Nume, Locuri_Disponibile, Facultate_ID

        querryString+=f'(ID, Nume, Locuri_Disponibile, Facultate_ID) VALUES ('
        try:
            querryString+= str(mydb.db.get_max_id('Specializari_SP')+1)
        except Exception as e:
            querryString+= '1'
        if self.name_insert_3.text()=='':
            raise Exception('Numele nu poate fi null')
        
        if self.prenume_insert_3.text()=='':
            self.prenume_insert_3.setText('-')           
        if self.email_insert_3.text()=='':
            self.email_insert_3.setText('-')
             
        querryString+=",'"+self.name_insert_3.text()+f"', '{self.prenume_insert_3.text()}','{self.email_insert_3.text()}')"
        print(querryString)
        try:
            mydb.db.insert_into_table('specializari_SP',querryString)
        except Exception as e:
            print(e)
        # self.set_filter_btn()
        self.set_filter_btn_specializari()
    
        
    
    def set_filter_btn_specializari(self):
        querryString = "WHERE "
        first = False
        
        if (self.name_filter_4.text()!=''):
            print(type(self.name_filter_4.text()))
            check_int= False
            try:
                value = int(self.name_filter_4.text())
                check_int = True
            except:
                check_int = False
            if check_int:
                if first == True:
                    querryString+=f"AND "   
                querryString+=f"Facultate_ID={self.name_filter_4.text()} "
                first = True
            else:
                if first == True:
                    querryString+=f"AND "
                try:   
                    querryString+=f"Facultate_ID='{mydb.db.selectare_id_facultate(self.name_filter_4.text())}' "
                except:
                    pass
            first = True 
        if (self.id_filter_3.text()!=''):

            querryString+=f"s.ID={self.id_filter_3.text()} "
            first = True
        if (self.name_filter_3.text()!=''):
            if first == True:
                querryString+=f"AND "   
            querryString+=f"s.Nume='{self.name_filter_3.text()}' "
            first = True
        print('Final ', querryString)
        orderString = 'ORDER BY '
        first = False
        print(querryString)     
        if self.sort_name_chckbox_3.isChecked():
            if self.sort_desc_ckbox_3.isChecked():
                
                orderString+='NUME DESC'
            else:
                orderString+='NUME ASC'
            first = True
        if self.sort_prenume_ckbox_3.isChecked():
            if first:
                if self.sort_desc_ckbox_3.isChecked():
                    
                    orderString+=', Locuri_Disponibile DESC'
                else:
                    orderString+=', Locuri_Disponibile ASC'
            else:
                if self.sort_desc_ckbox_3.isChecked():
                    
                    orderString+=' Locuri_Disponibile DESC'
                else:
                    orderString+=' Locuri_Disponibile ASC'
            first = True
        
        if self.sort_age_ckbox_3.isChecked():
            if first:
                if self.sort_desc_ckbox_3.isChecked():
                    
                    orderString+=', Facultate_ID DESC'
                else:
                    orderString+=', Facultate_ID ASC'
            else:
                if self.sort_desc_ckbox_3.isChecked():
                    
                    orderString+=' Facultate_ID DESC'
                else:
                    orderString+=' Facultate_ID ASC'
            first = True
        print('final order by ',orderString)
        if querryString!='WHERE ':
            if orderString!='ORDER BY ':
                querryString+=orderString
            output = mydb.db.select_specializari_facultati_where(querryString)
           
        else:
            if orderString!='ORDER BY ':
                # output = mydb.db.select_with_where(orderString,'Specializari_SP')
                output = mydb.db.select_specializari_facultati_where(querryString)
            else:
                output = mydb.db.select_specializari_facultati()
        self.create_table_facultati(SPECIALIZARI_HEADER,output,specializari=True)
        
    def delete_facultate(self):
        if self.id_delete_2.text() !='':
            querryString = ' Where ID='+self.id_delete_2.text()
        else:
            if self.name_delete_2.text()  != '':
                querryString = f" Where Nume='{self.name_delete_2.text()}'"
                
                
        mydb.db.delete_where('Facultati_SP',querryString)
        self.set_filter_btn()
            
    def insert_facultate(self):
        querryString = ''
            # INSERT INTO Facultati_SP (ID, Nume, Adresa, Telefon, Email)
# VALUES (4, 'Facultatea de Drept', 'Strada Dreptului, Suceava', '+40 230 111 222', 'info@facultatededrept.usv.ro');
        querryString+=f'(ID, Nume, Adresa, Telefon, Email) VALUES ('
        try:
            querryString+= str(mydb.db.get_max_id('Facultati_SP')+1)
        except Exception as e:
            querryString+= '1'
        if self.name_insert_2.text()=='':
            raise Exception('Numele nu poate fi null')
        if self.address_insert_2.text()=='':
            self.address_insert_2.setText('-')
        if self.prenume_insert_2.text()=='':
            self.prenume_insert_2.setText('-')           
        if self.email_insert_2.text()=='':
            self.email_insert_2.setText('-')
             
        querryString+=",'"+self.name_insert_2.text()+f"', '{self.address_insert_2.text() }', '{self.prenume_insert_2.text()}','{self.email_insert_2.text()}')"
        print(querryString)
        mydb.db.insert_into_table('facultati_SP',querryString)
        self.set_filter_btn()
    def set_content_page(self):
        self.stackedWidget.setCurrentIndex(1)
        
    def set_filter_btn(self):
        print('Im here')
        querryString = "WHERE "
        print(self.id_filter_2.text())
        first = False
        if (self.id_filter_2.text()!=''):

            querryString+=f"ID={self.id_filter_2.text()} "
            first = True
        if (self.name_filter_2.text()!=''):
            if first == True:
                querryString+=f"AND "   
            querryString+=f"Nume='{self.name_filter_2.text()}' "
            first = True
        print('final string is ', querryString)
        orderString = 'ORDER BY '
        first = False
        if self.sort_name_chckbox_2.isChecked():
            if self.sort_desc_ckbox_2.isChecked():
                
                orderString+='NUME DESC'
            else:
                orderString+='NUME ASC'
            first = True
        if self.sort_prenume_ckbox_2.isChecked():
            if first:
                if self.sort_desc_ckbox_2.isChecked():
                    
                    orderString+=', Adresa DESC'
                else:
                    orderString+=', Adresa ASC'
            else:
                if self.sort_desc_ckbox_2.isChecked():
                    
                    orderString+=' Adresa DESC'
                else:
                    orderString+=' Adresa ASC'
            first = True
        
        if self.sort_age_ckbox_2.isChecked():
            if first:
                if self.sort_desc_ckbox_2.isChecked():
                    
                    orderString+=', Telefon DESC'
                else:
                    orderString+=', Telefon ASC'
            else:
                if self.sort_desc_ckbox_2.isChecked():
                    
                    orderString+=' Telefon DESC'
                else:
                    orderString+=' Telefon ASC'
            first = True
        print('final order by ',orderString)
        if querryString!='WHERE ':
            if orderString!='ORDER BY ':
                querryString+=orderString
            output = mydb.db.select_with_where(querryString,'Facultati_SP')
        else:
            if orderString!='ORDER BY ':
                output = mydb.db.select_with_where(orderString,'Facultati_SP')
            else:
                output = mydb.db.select_all_from_facultati()
        self.create_table_facultati(["ID","Nume","Adresa","Telefon","Email" ],output)
        
    def exit_btn(self):
        sys.exit(0)
    def create_table_facultati(self,headerList, rowList,specializari=False,studenti=False):
        myTable = PrettyTable()
        myTable.field_names= headerList
        for row in rowList:
            vect =[]
            for item in row:
                vect.append(item)
            myTable.add_row(vect)
        if specializari:
            myrow = self.model_specializari.rowCount()
            self.model_specializari.insertRow(myrow)
            index = self.model_specializari.index(myrow)

            for item in myTable.get_string().split('\n'):
                myrow = self.model_specializari.rowCount()
                self.model_specializari.insertRow(myrow)
                index = self.model_specializari.index(myrow)
                # print(myTable.split())
                self.model_specializari.setData(index,item)
        elif studenti:
            myrow = self.model_studenti.rowCount()
            self.model_studenti.insertRow(myrow)
            index = self.model_studenti.index(myrow)

            for item in myTable.get_string().split('\n'):
                myrow = self.model_studenti.rowCount()
                self.model_studenti.insertRow(myrow)
                index = self.model_studenti.index(myrow)
                # print(myTable.split())
                self.model_studenti.setData(index,item)
        else:
            myrow = self.model.rowCount()
            self.model.insertRow(myrow)
            index = self.model.index(myrow)

            for item in myTable.get_string().split('\n'):
                myrow = self.model.rowCount()
                self.model.insertRow(myrow)
                index = self.model.index(myrow)
                # print(myTable.split())
                self.model.setData(index,item)
 
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.me_name.setText(_translate("MainWindow", "Gestionarea Studenților pe facultăți"))
        self.label_2.setText(_translate("MainWindow", "Șandru Paul"))
        self.exit_btn1.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))
        self.studenti_btn.setText(_translate("MainWindow", "Studenti_SP"))
        self.facultati_btn.setText(_translate("MainWindow", "Facultati_SP "))
        self.specializar_btn.setText(_translate("MainWindow", "Specializari_SP "))
        self.sort_age_ckbox_2.setText(_translate("MainWindow", "Telefon"))
        self.sort_desc_ckbox_2.setText(_translate("MainWindow", "Descrescător"))
        self.pushButton_6.setText(_translate("MainWindow", "Inserează "))
        self.pushButton_8.setText(_translate("MainWindow", "Afilșează"))
        self.label_52.setText(_translate("MainWindow", "Inserare facultate"))
        self.sort_name_chckbox_2.setText(_translate("MainWindow", "Nume"))
        self.label_51.setText(_translate("MainWindow", "Id"))
        self.pushButton_7.setText(_translate("MainWindow", "Șterge facultate"))
        self.label_50.setText(_translate("MainWindow", "Email"))
        self.label_46.setText(_translate("MainWindow", "Sortează după"))
        self.filter_name_2.setText(_translate("MainWindow", "Filtru"))
        self.lbl_name_studenti_sp_4.setText(_translate("MainWindow", "Facultati_SP"))
        self.label_44.setText(_translate("MainWindow", "Nume"))
        self.label_49.setText(_translate("MainWindow", "Adresa"))
        self.label_53.setText(_translate("MainWindow", "Șterge facultate"))
        self.label_48.setText(_translate("MainWindow", "Nume"))
        self.label_42.setText(_translate("MainWindow", "Id"))
        self.sort_prenume_ckbox_2.setText(_translate("MainWindow", "Adresa"))
        self.label_39.setText(_translate("MainWindow", "Nume"))
        self.label_47.setText(_translate("MainWindow", "Telefon"))
        self.lbl_name_studenti_sp.setText(_translate("MainWindow", "Studenti_SP"))
        self.filter_name.setText(_translate("MainWindow", "Filtru"))
        self.label_3.setText(_translate("MainWindow", "Id"))
        self.label_4.setText(_translate("MainWindow", "Nume"))
        self.label_5.setText(_translate("MainWindow", "Prenume"))
        self.label_6.setText(_translate("MainWindow", "Facultate"))
        self.label_8.setText(_translate("MainWindow", "Sortează după"))
        self.sort_name_chckbox.setText(_translate("MainWindow", "Nume"))
        self.sort_prenume_ckbox.setText(_translate("MainWindow", "Prenume"))
        self.sort_age_ckbox.setText(_translate("MainWindow", "Varsta"))
        self.sort_desc_ckbox.setText(_translate("MainWindow", "Descrescător"))
        self.pushButton.setText(_translate("MainWindow", "Afilșează"))
        self.label_7.setText(_translate("MainWindow", "Inserare student"))
        self.label_17.setText(_translate("MainWindow", "Nume"))
        self.label_18.setText(_translate("MainWindow", "Prenume"))
        self.label_19.setText(_translate("MainWindow", "Data_nasterii"))
        self.label_20.setText(_translate("MainWindow", "Telefon"))
        self.label_33.setText(_translate("MainWindow", "Email"))
        self.label_34.setText(_translate("MainWindow", "Adresa"))
        self.pushButton_4.setText(_translate("MainWindow", "Inserează"))
        self.label_35.setText(_translate("MainWindow", "Șterge student "))
        self.label_36.setText(_translate("MainWindow", "Id"))
        self.label_37.setText(_translate("MainWindow", "Nume"))
        self.label_38.setText(_translate("MainWindow", "Prenume"))
        self.pushButton_5.setText(_translate("MainWindow", "Șterge student"))
        self.label_41.setText(_translate("MainWindow", "Specializare"))
        self.pushButton_9.setText(_translate("MainWindow", "Inserează "))
        self.label_54.setText(_translate("MainWindow", "Facultate_ID"))
        self.pushButton_10.setText(_translate("MainWindow", "Afilșează"))
        self.label_55.setText(_translate("MainWindow", "Sortează după"))
        self.lbl_name_studenti_sp_5.setText(_translate("MainWindow", "Specializari_SP"))
        self.label_56.setText(_translate("MainWindow", "Inserare facultate"))
        self.label_45.setText(_translate("MainWindow", "Nume"))
        self.sort_prenume_ckbox_3.setText(_translate("MainWindow", "Locuri disponibile"))
        self.sort_desc_ckbox_3.setText(_translate("MainWindow", "Descrescător"))
        self.label_40.setText(_translate("MainWindow", "Nume"))
        self.sort_name_chckbox_3.setText(_translate("MainWindow", "Nume"))
        self.sort_age_ckbox_3.setText(_translate("MainWindow", "Facultate"))
        self.label_58.setText(_translate("MainWindow", "Șterge facultate"))
        self.label_59.setText(_translate("MainWindow", "Locuri_Disponibile "))
        self.label_60.setText(_translate("MainWindow", "Nume"))
        self.filter_name_3.setText(_translate("MainWindow", "Filtru"))
        self.pushButton_11.setText(_translate("MainWindow", "Șterge facultate"))
        self.label_43.setText(_translate("MainWindow", "Id"))
        self.label_61.setText(_translate("MainWindow", "Id"))
        self.label_62.setText(_translate("MainWindow", "Facultate"))
        
    def set_facultati_widget(self):
        conn = mydb.db.get_connection()

        self.content_widget.setCurrentIndex(0)
        
        rows = mydb.db.select_all_from_facultati()
        
        myTable = PrettyTable()
        myTable.field_names = ["ID","Nume","Adresa","Telefon","Email" ]
        
        for row in rows:
            vect =[]
            for item in row:
                vect.append(item)
            myTable.add_row(vect)
        
        myrow = self.model.rowCount()
        self.model.insertRow(myrow)
        index = self.model.index(myrow)
        # print(myTable.split())
        # self.model.setData(index,myTable.get_string())
        for item in myTable.get_string().split('\n'):
            myrow = self.model.rowCount()
            self.model.insertRow(myrow)
            index = self.model.index(myrow)
            # print(myTable.split())
            self.model.setData(index,item)
        
        # header = "ID\t  Nume\t\t\t\t Adresa\t\t\t Telefon\t\t\t Email"
        # myrow = self.model.rowCount()
        # self.model.insertRow(myrow)
        # index = self.model.index(myrow)
        # self.model.setData(index,header)
        # for row in rows:
        #     myrow = self.model.rowCount()
        #     self.model.insertRow(myrow)
        #     index = self.model.index(myrow)
        #     # creating the string 

        #     line =""
        #     id = 1
        #     for item in row:
        #         if id ==1:
        #             line+=str(item)
        #             line+="\t"
        #         else:
        #             line+=str(item)
        #             line+="\t\t\t"
        #         id+=1
        #     self.model.setData(index,line)
        
    def set_specialziare_widget(self):
        self.content_widget.setCurrentIndex(2)
        rows = mydb.db.select_specializari_facultati()
        self.create_table_facultati(['ID','Specializare','Facultate','Locuri disponibile'],rows,True)
        
        
        
    def set_studenti_widget(self):
        self.content_widget.setCurrentIndex(1)
        rows =mydb.db.select_Studenti_specializari()
        print(rows)
        self.create_table_facultati(STUDENTI_HEADER,rows,studenti=True)
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    
    MainWindow.show()
    sys.exit(app.exec_())
